### ISSUE TITLE
EventMachine 1.0.7 Breaks

### ISSUE THREAD

**Issue by rsiddle** [voloko/twitter-stream#43]
The update to Event Machine BufferTokenizer initalizer now gives wrong arguement amounts. 

``` ruby

 /Users/ryan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.7/lib/em/buftok.rb:15:in `initialize': wrong number of arguments (2 for 0..1) (ArgumentError)
    from /Users/ryan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/twitter-stream-0.1.16/lib/twitter/json_stream.rb:206:in `new'
    from /Users/ryan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/twitter-stream-0.1.16/lib/twitter/json_stream.rb:206:in `reset_state'

```

See https://github.com/eventmachine/eventmachine/commit/e385d0ad491d911ba49a4f26b03b7635b9d28df7#diff-a6fc4ed08b8c357cd44b13bcefb869faL25

**Comment by cantino** [comment]
https://github.com/dsander/twitter-stream/tree/huginn fixes this I think.  I'm also trying to update to the newest version of the `http` gem due to a security issue.  http://www.42.mach7x.com/2015/04/15/osvdb-119927-http-gem-for-ruby-ssl-certificate-validation-mitm-spoofing/

**Comment by cantino** [comment]
https://github.com/cantino/twitter-stream/tree/huginn seems to work for me.
